//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAnnotator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class annotate_dbEntities : DbContext
    {
        public annotate_dbEntities()
            : base("name=annotate_dbEntities")
        {
        }
    
        public virtual DbSet<NewsAnnotate> NewsAnnotates { get; set; }
    }
}
